// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// This file implements generation of interpreter IR from JIT optimized GenTrees.
// When DOTNET_InterpOptMethod is set, the JIT runs its normal optimization passes
// but instead of generating native code, it translates the optimized LIR into
// interpreter bytecodes that can be executed by the interpreter execution engine.

#include "jitpch.h"

#ifdef FEATURE_INTERPRETER

// Include interpreter opcode definitions for the dump tables / INTOP_ enum.
#include "../interpreter/inc/intopsshared.h"

// Build the shared interpreter method representation (InterpMethod /
// InterpByteCodeStart) with the compiler-side handle type. interpmethod.h carries
// only the runtime structures and constants (no MethodSet), so it can be included
// here without clashing with the JIT's own MethodSet.
#define INTERPRETER_COMPILER_INTERNAL
#include "../interpreter/inc/interpmethod.h"

#ifdef DEBUG
// Opcode metadata used to disassemble the generated bytecode for the JIT dump.
// The tables are generated from the shared intops.def, so no opcode information
// is duplicated here. The output format matches the interpreter library's own
// dump (DumpCompiledIns / DumpCompiledCode in interpreter/compiler.cpp). This
// JIT-local disassembler is a temporary validation aid; reusing the interpreter's
// InterpDumpIR (which lives in the separate clrinterpreter library) is a follow-up.
static const char* const s_interpOpNames[] = {
#define OPDEF(name, str, len, dvars, svars, argType) str,
#include "../interpreter/inc/intops.def"
#undef OPDEF
};

static const uint8_t s_interpOpLen[] = {
#define OPDEF(name, str, len, dvars, svars, argType) (uint8_t)(len),
#include "../interpreter/inc/intops.def"
#undef OPDEF
};

static const int s_interpOpDVars[] = {
#define OPDEF(name, str, len, dvars, svars, argType) (dvars),
#include "../interpreter/inc/intops.def"
#undef OPDEF
};

static const int s_interpOpSVars[] = {
#define OPDEF(name, str, len, dvars, svars, argType) (svars),
#include "../interpreter/inc/intops.def"
#undef OPDEF
};

// Mirrors ConvertOffset() in interpreter/compiler.cpp: the byte offset of an
// instruction, accounting for the InterpByteCodeStart header preceding the codes.
static uint32_t interpConvertOffset(int32_t offset)
{
    return offset * sizeof(int32_t) + sizeof(void*);
}

// Print the trailing immediate(s) / branch target of an instruction, matching the
// interpreter's DumpInsData for the opcodes we currently emit. Branch opcodes
// encode their target as a relative offset in the last slot (cf.
// InterpOpIsCondBranch / InterpOpIsUncondBranch in interpreter/intops.h).
static void dumpInterpInsData(int32_t insOffset, const int32_t* p, const int32_t* insEnd, int32_t opcode)
{
    const bool isBranch = (opcode == INTOP_BR) ||
                          (opcode >= INTOP_BRFALSE_I4 && opcode <= INTOP_BLT_UN_R8) ||
                          (opcode == INTOP_BLT_I4_IMM);
    if (isBranch && (p < insEnd))
    {
        for (; p < insEnd - 1; p++)
            printf(" %d", *p);
        printf(" IR_%04x", insOffset + *p);
    }
    else
    {
        for (; p < insEnd; p++)
            printf(" %d", *p);
    }
}

// Print a single instruction, matching DumpCompiledIns in interpreter/compiler.cpp.
static void dumpInterpInst(const int32_t* codeBase, const int32_t* ip)
{
    const int32_t opcode    = *ip;
    const int32_t insOffset = (int32_t)(ip - codeBase);

    printf("%04x: IR_%04x: %-14s", (int32_t)interpConvertOffset(insOffset), insOffset, s_interpOpNames[opcode]);

    const int32_t* p = ip + 1;
    if (s_interpOpDVars[opcode] > 0)
        printf(" [%d <-", *p++);
    else
        printf(" [nil <-");

    if (s_interpOpSVars[opcode] > 0)
    {
        for (int i = 0; i < s_interpOpSVars[opcode]; i++)
            printf(" %d", *p++);
        printf("],");
    }
    else
    {
        printf(" nil],");
    }

    const int32_t  len    = s_interpOpLen[opcode];
    const int32_t* insEnd = ip + (len != 0 ? len : 1);
    dumpInterpInsData(insOffset, p, insEnd, opcode);
    printf("\n");
}

// Disassemble the generated bytecode buffer, matching DumpCompiledCode.
static void dumpInterpCode(const int32_t* code, int32_t codeSizeSlots)
{
    const int32_t* ip  = code;
    const int32_t* end = code + codeSizeSlots;
    while (ip < end)
    {
        dumpInterpInst(code, ip);
        const int32_t len = s_interpOpLen[*ip];
        ip += (len != 0 ? len : 1);
    }
    printf("End of method: %04x: IR_%04x\n", (int32_t)interpConvertOffset((int32_t)(ip - code)), (int32_t)(ip - code));
}
#endif // DEBUG

// Helper to emit an int32_t value into the bytecode buffer and advance the pointer.
static int32_t* emitInt(int32_t* ip, int32_t value)
{
    *ip = value;
    return ip + 1;
}

//------------------------------------------------------------------------
// generateInterpIR: Generate interpreter bytecodes from optimized LIR
//
// Arguments:
//   methodCodePtr  [OUT] - address of generated interpreter bytecodes
//   methodCodeSize [OUT] - size of the generated bytecodes
//
// This is called instead of genGenerateCode when InterpOptMethod matches.
//
void Compiler::generateInterpIR(void** methodCodePtr, uint32_t* methodCodeSize)
{
#ifdef DEBUG
    printf("JIT->InterpIR: Generating interpreter IR for method %s\n", info.compFullName);
#endif

    // ============================================================
    // Phase 1: Map JIT locals to interpreter variable offsets
    // ============================================================

    // We assign each JIT local a sequential 8-byte slot.
    // The arg variables come first (for correct ABI layout), then locals.
    unsigned* varOffsetMap = new (this, CMK_Generic) unsigned[lvaCount];
    unsigned nextVarOffset = 0;

    // Assign offsets to all JIT locals
    for (unsigned i = 0; i < lvaCount; i++)
    {
        LclVarDsc* lcl = lvaGetDesc(i);

        // Skip the OutgoingArgSpace pseudo-variable
        if (lcl->lvIsParam || !lcl->lvIsStructField)
        {
            varOffsetMap[i] = nextVarOffset;
            nextVarOffset += INTERP_STACK_SLOT_SIZE;
        }
        else
        {
            varOffsetMap[i] = nextVarOffset;
            nextVarOffset += INTERP_STACK_SLOT_SIZE;
        }
    }

    // Reserve a pool of temp var offsets for intermediate values
    // (e.g., constants used in comparisons)
    unsigned tempVarBase = nextVarOffset;
    unsigned tempVarCount = 0;
    const unsigned MAX_TEMP_VARS = 64;

    auto allocTempVar = [&]() -> int32_t {
        unsigned offset = tempVarBase + tempVarCount * INTERP_STACK_SLOT_SIZE;
        tempVarCount++;
        assert(tempVarCount <= MAX_TEMP_VARS);
        return (int32_t)offset;
    };

    // ============================================================
    // Phase 2: Map GenTree nodes to interpreter var offsets
    // ============================================================

    // In LIR, each value-producing node needs a "result var" in the interpreter.
    // For LCL_VAR loads, the result is the JIT local's offset.
    // For other value-producing nodes (CNS_INT, ADD, etc.), we assign a temp.
    //
    // We use a map from GenTree* -> interpreter var offset.

    // Count nodes to size the map
    unsigned nodeCount = 0;
    for (BasicBlock* block = fgFirstBB; block != nullptr; block = block->Next())
    {
        for (GenTree* node = block->GetFirstLIRNode(); node != nullptr; node = node->gtNext)
        {
            nodeCount++;
        }
    }

    // Simple mapping: GenTree pointer -> interp var offset
    // Using a fixed-size array indexed by gtTreeID would be ideal but
    // let's use a simple linear search for the prototype.
    struct NodeVarMapping
    {
        GenTree* node;
        int32_t  interpVarOffset;
    };
    NodeVarMapping* nodeMap = new (this, CMK_Generic) NodeVarMapping[nodeCount];
    unsigned nodeMapCount = 0;

    auto setNodeVar = [&](GenTree* node, int32_t offset) {
        nodeMap[nodeMapCount].node = node;
        nodeMap[nodeMapCount].interpVarOffset = offset;
        nodeMapCount++;
    };

    auto getNodeVar = [&](GenTree* node) -> int32_t {
        for (unsigned i = 0; i < nodeMapCount; i++)
        {
            if (nodeMap[i].node == node)
                return nodeMap[i].interpVarOffset;
        }
        // Should not happen
        assert(!"GenTree node not found in nodeMap");
        return -1;
    };

    // ============================================================
    // Phase 3: Emit interpreter bytecodes
    // ============================================================

    // First pass: compute an upper bound on the bytecode size for allocation.
    // Each node emits at most ~8 slots (e.g. a JCC: lazy LDC + safepoint + branch),
    // and each block adds per-block overhead (entry/backward-branch safepoints and
    // a BBJ_ALWAYS terminator) that is not accounted for by nodeCount.
    unsigned maxCodeSlots = nodeCount * 8 + fgBBcount * 4 + 16;
    int32_t* codeBuffer = new (this, CMK_Generic) int32_t[maxCodeSlots];
    int32_t* ip = codeBuffer;

    // Track basic block native offsets for branch patching
    struct BBOffset
    {
        BasicBlock* bb;
        int32_t     nativeOffset; // in int32_t slots from start
    };
    BBOffset* bbOffsets = new (this, CMK_Generic) BBOffset[fgBBcount + 1];
    unsigned bbOffsetsCount = 0;

    // Track branch relocations
    struct BranchReloc
    {
        int32_t*    patchLocation;    // pointer into codeBuffer where target offset goes
        int32_t     instrOffset;      // offset of the branch instruction (in int32_t slots)
        BasicBlock* targetBB;
    };
    // A relocation is emitted per conditional branch (a JCC node, counted in
    // nodeCount) and per BBJ_ALWAYS terminator (one per block, not a node), so
    // bound the array by nodeCount + fgBBcount.
    BranchReloc* branchRelocs = new (this, CMK_Generic) BranchReloc[nodeCount + fgBBcount + 1];
    unsigned branchRelocCount = 0;

    // Track the last CMP node's operands for combining with JCC
    GenTree* lastCmpOp1 = nullptr;
    GenTree* lastCmpOp2 = nullptr;

    for (BasicBlock* block = fgFirstBB; block != nullptr; block = block->Next())
    {
        // Record BB's native offset
        bbOffsets[bbOffsetsCount].bb = block;
        bbOffsets[bbOffsetsCount].nativeOffset = (int32_t)(ip - codeBuffer);
        bbOffsetsCount++;

        // Emit INTOP_SAFEPOINT at method entry (first block)
        if (block == fgFirstBB)
        {
            ip = emitInt(ip, INTOP_SAFEPOINT);
        }

        for (GenTree* node = block->GetFirstLIRNode(); node != nullptr; node = node->gtNext)
        {
            switch (node->OperGet())
            {
                case GT_IL_OFFSET:
                    // Skip - no interpreter equivalent needed
                    break;

                case GT_LCL_VAR:
                {
                    // A local variable load - map to the JIT local's interpreter offset
                    unsigned lclNum = node->AsLclVar()->GetLclNum();
                    setNodeVar(node, (int32_t)varOffsetMap[lclNum]);
                    break;
                }

                case GT_CNS_INT:
                {
                    // Integer constant - allocate a temp var and emit LDC.
                    int32_t tempOffset = allocTempVar();
                    setNodeVar(node, tempOffset);

                    ssize_t value = node->AsIntCon()->IconValue();

                    // Check whether the consumer will handle the value inline
                    // (so we can skip emitting a separate load). This applies
                    // to both contained and non-contained constants:
                    //  - STORE_LCL_VAR with data == this node  → emits LDC inline
                    //  - ADD with op2 == this node (contained) → STORE_LCL_VAR emits ADD_I4_IMM
                    //  - CMP with op2 == this node             → JCC emits BLT_I4_IMM or loads lazily
                    {
                        GenTree* user = node->gtNext;
                        while (user != nullptr && user->OperIs(GT_IL_OFFSET))
                            user = user->gtNext;

                        bool handledInline = false;
                        if (user != nullptr)
                        {
                            if (user->OperIsLocalStore() && user->AsLclVar()->Data() == node)
                            {
                                handledInline = true;
                            }
                            else if (node->isContained() && user->OperIs(GT_ADD) && user->AsOp()->gtOp2 == node)
                            {
                                handledInline = true;
                            }
                            else if (user->OperIs(GT_CMP) && user->AsOp()->gtOp2 == node)
                            {
                                handledInline = true;
                            }
                        }

                        if (handledInline)
                            break;
                    }

                    if (value == 0)
                    {
                        // INTOP_LDC_I4_0: opcode + dvar = 2 slots
                        ip = emitInt(ip, INTOP_LDC_I4_0);
                        ip = emitInt(ip, tempOffset);
                    }
                    else
                    {
                        // INTOP_LDC_I4: opcode + dvar + value = 3 slots
                        ip = emitInt(ip, INTOP_LDC_I4);
                        ip = emitInt(ip, tempOffset);
                        ip = emitInt(ip, (int32_t)value);
                    }
                    break;
                }

                case GT_STORE_LCL_VAR:
                {
                    unsigned dstLclNum = node->AsLclVar()->GetLclNum();
                    int32_t dstOffset = (int32_t)varOffsetMap[dstLclNum];
                    GenTree* data = node->AsLclVar()->Data();

                    if (data->OperIs(GT_LCL_VAR))
                    {
                        // MOV_4: copy from one local to another
                        int32_t srcOffset = getNodeVar(data);
                        if (srcOffset != dstOffset)
                        {
                            ip = emitInt(ip, INTOP_MOV_4);
                            ip = emitInt(ip, dstOffset);
                            ip = emitInt(ip, srcOffset);
                        }
                    }
                    else if (data->OperIs(GT_CNS_INT))
                    {
                        ssize_t value = data->AsIntCon()->IconValue();
                        if (value == 0)
                        {
                            ip = emitInt(ip, INTOP_LDC_I4_0);
                            ip = emitInt(ip, dstOffset);
                        }
                        else
                        {
                            ip = emitInt(ip, INTOP_LDC_I4);
                            ip = emitInt(ip, dstOffset);
                            ip = emitInt(ip, (int32_t)value);
                        }
                    }
                    else if (data->OperIs(GT_ADD))
                    {
                        GenTree* op1 = data->AsOp()->gtOp1;
                        GenTree* op2 = data->AsOp()->gtOp2;

                        if (op2->OperIs(GT_CNS_INT) && op2->isContained())
                        {
                            // ADD_I4_IMM: dest = src + imm
                            int32_t srcOffset = getNodeVar(op1);
                            int32_t immValue = (int32_t)op2->AsIntCon()->IconValue();
                            ip = emitInt(ip, INTOP_ADD_I4_IMM);
                            ip = emitInt(ip, dstOffset);
                            ip = emitInt(ip, srcOffset);
                            ip = emitInt(ip, immValue);
                        }
                        else
                        {
                            // ADD_I4: dest = src1 + src2
                            int32_t src1Offset = getNodeVar(op1);
                            int32_t src2Offset = getNodeVar(op2);
                            ip = emitInt(ip, INTOP_ADD_I4);
                            ip = emitInt(ip, dstOffset);
                            ip = emitInt(ip, src1Offset);
                            ip = emitInt(ip, src2Offset);
                        }
                    }
                    else
                    {
                        // Generic case: MOV from the data node's result var
                        int32_t srcOffset = getNodeVar(data);
                        if (srcOffset != dstOffset)
                        {
                            ip = emitInt(ip, INTOP_MOV_4);
                            ip = emitInt(ip, dstOffset);
                            ip = emitInt(ip, srcOffset);
                        }
                    }

                    // Update node mapping to the destination var
                    setNodeVar(node, dstOffset);
                    break;
                }

                case GT_ADD:
                {
                    // In LIR, ADD results are typically consumed by STORE_LCL_VAR
                    // which handles the emission. Just record the var mapping here.
                    // If the ADD is NOT consumed by a STORE_LCL_VAR, we'd need to
                    // emit it here, but for the current benchmark this doesn't occur.
                    int32_t tempOffset = allocTempVar();
                    setNodeVar(node, tempOffset);
                    break;
                }

                case GT_CMP:
                {
                    // Save CMP operands for the following JCC
                    lastCmpOp1 = node->AsOp()->gtOp1;
                    lastCmpOp2 = node->AsOp()->gtOp2;
                    break;
                }

                case GT_JCC:
                {
                    assert(lastCmpOp1 != nullptr && lastCmpOp2 != nullptr);
                    assert(block->KindIs(BBJ_COND));

                    GenCondition cond = node->AsCC()->gtCondition;

                    // The true target is where JCC branches to when condition is true
                    BasicBlock* trueTarget = block->GetTrueTarget();
                    bool isBackwardBranch = trueTarget->HasFlag(BBF_BACKWARD_JUMP_TARGET);

                    // For backward SLT branches where op2 is a constant,
                    // use the combined INTOP_BLT_I4_IMM which includes an inline
                    // safepoint check and folds the immediate into the instruction.
                    // Format: [opcode] [svar] [imm_i4] [branch_offset]
                    if (isBackwardBranch &&
                        cond.GetCode() == GenCondition::SLT &&
                        lastCmpOp2->OperIs(GT_CNS_INT))
                    {
                        int32_t src1Offset = getNodeVar(lastCmpOp1);
                        int32_t immValue = (int32_t)lastCmpOp2->AsIntCon()->IconValue();

                        int32_t branchInstrOffset = (int32_t)(ip - codeBuffer);
                        ip = emitInt(ip, INTOP_BLT_I4_IMM);
                        ip = emitInt(ip, src1Offset);
                        ip = emitInt(ip, immValue);
                        branchRelocs[branchRelocCount].patchLocation = ip;
                        branchRelocs[branchRelocCount].instrOffset = branchInstrOffset;
                        branchRelocs[branchRelocCount].targetBB = trueTarget;
                        branchRelocCount++;
                        ip = emitInt(ip, 0); // placeholder

                        lastCmpOp1 = nullptr;
                        lastCmpOp2 = nullptr;
                        break;
                    }

                    int32_t src1Offset = getNodeVar(lastCmpOp1);

                    // If op2 is a contained constant whose LDC was skipped (because
                    // CMP was listed as an inline consumer), emit it now for the
                    // generic branch path.
                    if (lastCmpOp2->OperIs(GT_CNS_INT) && lastCmpOp2->isContained())
                    {
                        int32_t tempOffset = getNodeVar(lastCmpOp2);
                        ssize_t cmpValue = lastCmpOp2->AsIntCon()->IconValue();
                        if (cmpValue == 0)
                        {
                            ip = emitInt(ip, INTOP_LDC_I4_0);
                            ip = emitInt(ip, tempOffset);
                        }
                        else
                        {
                            ip = emitInt(ip, INTOP_LDC_I4);
                            ip = emitInt(ip, tempOffset);
                            ip = emitInt(ip, (int32_t)cmpValue);
                        }
                    }
                    int32_t src2Offset = getNodeVar(lastCmpOp2);

                    // Map GenCondition to interpreter branch opcode
                    InterpOpcode branchOp;
                    switch (cond.GetCode())
                    {
                        case GenCondition::SLT: branchOp = INTOP_BLT_I4; break;
                        case GenCondition::SLE: branchOp = INTOP_BLE_I4; break;
                        case GenCondition::SGE: branchOp = INTOP_BGE_I4; break;
                        case GenCondition::SGT: branchOp = INTOP_BGT_I4; break;
                        case GenCondition::EQ:  branchOp = INTOP_BEQ_I4; break;
                        case GenCondition::NE:  branchOp = INTOP_BNE_UN_I4; break;
                        case GenCondition::ULT: branchOp = INTOP_BLT_UN_I4; break;
                        case GenCondition::ULE: branchOp = INTOP_BLE_UN_I4; break;
                        case GenCondition::UGE: branchOp = INTOP_BGE_UN_I4; break;
                        case GenCondition::UGT: branchOp = INTOP_BGT_UN_I4; break;
                        default:
                            assert(!"Unhandled GenCondition in interpIR");
                            branchOp = INTOP_BLT_I4;
                            break;
                    }

                    // Emit INTOP_SAFEPOINT before backward branches (non-IMM path)
                    if (isBackwardBranch)
                    {
                        ip = emitInt(ip, INTOP_SAFEPOINT);
                    }
                    int32_t branchInstrOffset = (int32_t)(ip - codeBuffer);
                    ip = emitInt(ip, branchOp);
                    ip = emitInt(ip, src1Offset);
                    ip = emitInt(ip, src2Offset);
                    branchRelocs[branchRelocCount].patchLocation = ip;
                    branchRelocs[branchRelocCount].instrOffset = branchInstrOffset;
                    branchRelocs[branchRelocCount].targetBB = trueTarget;
                    branchRelocCount++;
                    ip = emitInt(ip, 0); // placeholder

                    lastCmpOp1 = nullptr;
                    lastCmpOp2 = nullptr;
                    break;
                }

                case GT_RETURN:
                {
                    GenTree* retVal = node->AsOp()->GetReturnValue();
                    if (retVal != nullptr)
                    {
                        int32_t srcOffset = getNodeVar(retVal);
                        ip = emitInt(ip, INTOP_RET);
                        ip = emitInt(ip, srcOffset);
                    }
                    else
                    {
                        ip = emitInt(ip, INTOP_RET_VOID);
                    }
                    break;
                }

                default:
                    // For now, skip unhandled nodes
#ifdef DEBUG
                    printf("JIT->InterpIR: Unhandled node: %s\n", GenTree::OpName(node->OperGet()));
#endif
                    break;
            }
        }

        // For BBJ_ALWAYS blocks, emit an unconditional branch if target is not the next block
        if (block->KindIs(BBJ_ALWAYS))
        {
            BasicBlock* target = block->GetTarget();
            BasicBlock* nextBlock = block->Next();
            if (target != nextBlock)
            {
                // Emit INTOP_SAFEPOINT before backward branches
                if (target->HasFlag(BBF_BACKWARD_JUMP_TARGET))
                {
                    ip = emitInt(ip, INTOP_SAFEPOINT);
                }
                int32_t brInstrOffset = (int32_t)(ip - codeBuffer);
                ip = emitInt(ip, INTOP_BR);
                branchRelocs[branchRelocCount].patchLocation = ip;
                branchRelocs[branchRelocCount].instrOffset = brInstrOffset;
                branchRelocs[branchRelocCount].targetBB = target;
                branchRelocCount++;
                ip = emitInt(ip, 0); // placeholder
            }
        }
    }

    int32_t codeSlots = (int32_t)(ip - codeBuffer);
    int32_t codeSizeBytes = codeSlots * sizeof(int32_t);

    // ============================================================
    // Phase 4: Patch branch relocations
    // ============================================================

    for (unsigned i = 0; i < branchRelocCount; i++)
    {
        BasicBlock* targetBB = branchRelocs[i].targetBB;
        int32_t targetAbsOffset = -1;

        for (unsigned j = 0; j < bbOffsetsCount; j++)
        {
            if (bbOffsets[j].bb == targetBB)
            {
                targetAbsOffset = bbOffsets[j].nativeOffset;
                break;
            }
        }
        assert(targetAbsOffset >= 0);
        // The interpreter uses RELATIVE branch offsets: ip += offset
        int32_t relativeOffset = targetAbsOffset - branchRelocs[i].instrOffset;
        *branchRelocs[i].patchLocation = relativeOffset;
    }

    // Dump the generated interpreter bytecode into the JIT dump (DOTNET_JitDump).
#ifdef DEBUG
    if (verbose)
    {
        printf("\nGenerated interpreter IR for %s [%d slots]:\n", info.compFullName, codeSlots);
        dumpInterpCode(codeBuffer, codeSlots);
    }
#endif

    // ============================================================
    // Phase 5: Build output in interpreter format
    // ============================================================

    // Calculate total var stack size (all JIT locals + temps), aligned to the
    // interpreter frame alignment so the next stacked frame stays aligned.
    unsigned allocaSize = nextVarOffset + tempVarCount * INTERP_STACK_SLOT_SIZE;
    allocaSize          = (allocaSize + (INTERP_STACK_ALIGNMENT - 1)) & ~(INTERP_STACK_ALIGNMENT - 1);
    int32_t totalAllocaSize = (int32_t)allocaSize;

    // Calculate args size. Only single-slot (<= 8 byte) parameters are currently
    // supported (anything else is rejected before we get here), so each argument
    // occupies exactly one interpreter stack slot.
    int32_t argsSize = (int32_t)(info.compArgsCount * INTERP_STACK_SLOT_SIZE);

    // Memory layout:
    //   InterpByteCodeStart  (8 bytes - pointer to InterpMethod)
    //   bytecodes            (codeSizeBytes)
    //   InterpMethod         (sizeof(InterpMethod))

    uint32_t headerSize = sizeof(InterpByteCodeStart);
    uint32_t interpMethodSize = sizeof(InterpMethod);

    // Align InterpMethod to pointer size
    uint32_t bytecodeEnd = headerSize + codeSizeBytes;
    uint32_t interpMethodOffset = (bytecodeEnd + sizeof(void*) - 1) & ~(sizeof(void*) - 1);
    uint32_t totalSize = interpMethodOffset + interpMethodSize;

    // Use a simple heap allocation for interpreter bytecodes.
    // We must NOT use allocMem (via CEEJitInfo) because that registers the code
    // with EEJitManager which expects native code metadata (unwind info, etc.).
    uint8_t* base = (uint8_t*)malloc(totalSize);
    memset(base, 0, totalSize);

    // Write InterpByteCodeStart header: pointer to InterpMethod
    InterpMethod* pMethod = (InterpMethod*)(base + interpMethodOffset);
    memcpy(base, &pMethod, sizeof(InterpMethod*));

    // Copy bytecodes
    memcpy(base + headerSize, codeBuffer, codeSizeBytes);

    // Write InterpMethod
    pMethod->methodHnd = info.compMethodHnd;
    pMethod->argsSize = argsSize;
    pMethod->allocaSize = totalAllocaSize;
    pMethod->pDataItems = nullptr;
    pMethod->pCallStub = nullptr;
    pMethod->initLocals = ((info.compFlags & CORINFO_FLG_CONSTRUCTOR) != 0) || info.compInitMem;
    pMethod->unmanagedCallersOnly = false;
    pMethod->publishSecretStubParam = false;
    pMethod->codeSize = codeSlots;
#if DEBUG
    pMethod->self = pMethod;
#endif

    *methodCodePtr = base;
    *methodCodeSize = totalSize;

#ifdef DEBUG
    printf("JIT->InterpIR: Generated %d bytecode slots (%d bytes), allocaSize=%d, argsSize=%d, totalSize=%u\n",
           codeSlots, codeSizeBytes, totalAllocaSize, argsSize, totalSize);
#endif
}

#endif // FEATURE_INTERPRETER
